### ISSUE TITLE
Unable to Start MC1.6.2-0.7.4.dev.12

### ISSUE THREAD

**Issue by t999uk** [RS485/LogisticsPipes#181]
loads fine on client but when trying to start the mod on a server the following error occurs

running the latest version of forge .859

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen

...

logisticspipes.LogisticsPipes.init(LogisticsPipes.java:261)

full crash log
http://pastebin.com/uruvWFSK

**Comment by davboecki** [comment]
Should be fixed by https://github.com/RS485/LogisticsPipes-Dev/commit/4b9367b428ed628110425fb318b78bf8fa70759b

**Comment by t999uk** [comment]
yes its working now thanks for the quick fix

**Comment by mvanderlee** [comment]
Still happens for me using FTB Direwolf20 1.6.4.  (LogisticsPipes-MC1.6.4-0.7.4.dev.102)
Also tried with last jenkins build http://ci.thezorro266.com/job/LogisticsPipes-Dev/113/

full crash log
http://pastebin.com/109BpNFg

**Comment by davboecki** [comment]
Could you open a new issue because this is a completely different issue.
